[build]
  base = "Server"
  functions = "netlify/functions"

[functions]
  included_files = [
    "node_modules/pdfkit/**/*",
    "node_modules/pdfkit/js/data/**/*",
    "assests/**/*"
  ]
  node_bundler = "zisi"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

